<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use phpDocumentor\Reflection\Types\Self_;

/**
 * @package App\Models
 *
 * @property string $name
 * @property string $phone
 * @property string $company
 * @property string $title
 * @property string $message
 * @property string $file
 * @property int $user_id
 *
 */
class Order extends Model
{
    use HasFactory;

    /**
     * @var string[]
     */
    protected $fillable = [
        'name',
        'phone',
        'company',
        'title',
        'message',
        'file',
        'user_id',
    ];

    /**
     * @return false|string
     */
    public function getFileAttribute($file)
    {
        if(!$file){
            return false;
        }
        $url = Storage::url($file);
        return $url;
    }

    public function save(array $options = [])
    {
        $this->user_id = Auth::id();
        return parent::save($options); // TODO: Change the autogenerated stub
    }

    public function saveFile($file){
        $upload_folder = 'public';
        $filename = date('h-m-Y-m-d') . '_' . $file->getClientOriginalName();
        Storage::putFileAs($upload_folder, $file, $filename);
        return $filename;
    }
}
