<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

/**
 * @package App\Models
 *
 * @property string $name
 * @property string $phone
 * @property string $company
 * @property string $title
 * @property string $message
 * @property string $file
 * @property int $user_id
 *
 */
class Order extends Model
{
    use HasFactory;

    /**
     * @var string[]
     */
    protected $fillable = [
        'name',
        'phone',
        'company',
        'title',
        'message',
        'file',
        'user_id',
    ];

    /**
     * @return false|string
     */
    public function getFileAttribute($file)
    {
        if(!$file){
            return false;
        }
        $url = Storage::url($file);
        return $url;
    }

    public function save(array $options = [])
    {
        $file = $options['file'];
        $fileName = $this->saveFile($file);

        return parent::save($options); // TODO: Change the autogenerated stub
    }

    private function saveFile($file){
        $fileName = '';

        return $fileName;
    }
}
